version: "3.8"

services:
  blog:
    image: deweiliu/blog:latest
    build:
      context: ./src
      dockerfile: Dockerfile
      x-bake:
        platforms:
          - linux/amd64
    ports:
      - "80:80"
    restart: always
    container_name: blog-container

