version: "3.8"

services:
  wordpress:
    image: deweiliu/wordpress:latest
    build:
      context: ./src
      dockerfile: Dockerfile
      x-bake:
        platforms:
          - linux/amd64
          - linux/arm64
    ports:
      - "80:80"
    restart: always
    container_name: wordpress-container

